---
#More argument: https://containrrr.dev/watchtower/arguments/
version: "3.9"
services:
  watchtower:
    image: taufiq14s/watchtower-ecr:latest
    container_name: watchtower
    restart: always
    env_file:
      - .env
    ports: #Expose port for enable HTTP Mode (opsional)
      - "127.0.0.1:9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #Docker Sock
      - ./aws-ecr-credentials-helper/docker/config.json:/config.json #Docker Config
      - ${HOME}/.aws:/.aws #AWS CLI Config
