---
#More argument: https://containrrr.dev/watchtower/arguments/
version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    restart: always
    env_file:
      - .env
    ports: #Expose port for enable HTTP Mode (optional)
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #Docker Sock
      - ./aws-ecr-credentials-helper/docker/config.json:/config.json:ro #Docker Config
      - ./aws-ecr-credentials-helper/:/go/bin:ro
      - ${HOME}/.aws:/./aws